### PR TITLE
Add countries to registry

### PR DESCRIPTION
**Pull request by Schrank**
This is an interesting list with non ISO keys. Not sure why and why it is not complete - or at least tries to, but here are a few more :-)

### CODE REVIEW

**Comment by vertic4l** [comment]
Well, thanks but what would be more important would be to have the profile updated for Migration Assistant v5 with PHP 8.x

**Comment by Schrank** [comment]
Thanks for the feedback, but I fix problems I have. And I ran the migration with PHP 8.1 so it seems at least for orders and customers it is compatible :-)

**Comment by vertic4l** [comment]
I can't activate the profile in the admin due to interface issues of the SalesChannelConverter.

You are not using v5 of the Migration Assistent?

**Comment by Schrank** [comment]
Nope, because composer installed v4, because the profile is not compatible

**Comment by mitelg** [comment]
merged with dbddfcbe711105a68f76ad3ab8db765781b108b2

thanks for your contribution @Schrank 👍🎉💙

**Pull request closed without merging**
